/**
 * Percentile parity against NumPy.
 *
 * Fixtures come from `np.nanpercentile(..., method="linear")` on NumPy 2.4.6,
 * generated by scripts in the chunk-2 commit. These endpoints define the frozen
 * stretch bounds for the whole session, so an interpolation mismatch here would
 * shift every risk map and every score by a constant the rest of the code has no
 * way to detect.
 */

import { describe, expect, it } from "vitest";
import fixtures from "../fixtures/percentiles.json";
import { hashArray, nanExtent, nanMean, nanPercentiles } from "../../src/core/stats";

interface PercentileCase {
  name: string;
  values: (number | null)[];
  percentiles: number[];
  expected: number[];
}

describe("nanPercentiles", () => {
  for (const testCase of fixtures as PercentileCase[]) {
    it(`matches numpy linear interpolation: ${testCase.name}`, () => {
      const values = Float64Array.from(testCase.values.map((v) => (v === null ? NaN : v)));
      const actual = nanPercentiles(values, testCase.percentiles);

      expect(actual).toHaveLength(testCase.expected.length);
      for (let i = 0; i < actual.length; i++) {
        expect(Math.abs(actual[i] - testCase.expected[i])).toBeLessThan(1e-12);
      }
    });
  }

  it("returns NaN for every percentile when nothing is finite", () => {
    const values = Float64Array.from([NaN, NaN, NaN]);
    expect(nanPercentiles(values, [5, 50, 95]).every(Number.isNaN)).toBe(true);
  });

  it("honours the mask", () => {
    const values = Float64Array.from([1, 2, 3, 1000]);
    const mask = Uint8Array.from([1, 1, 1, 0]);
    expect(nanPercentiles(values, [100], mask)[0]).toBe(3);
  });
});

describe("nanMean and nanExtent", () => {
  it("ignores NaN and masked cells", () => {
    const values = Float64Array.from([2, NaN, 4, 99]);
    const mask = Uint8Array.from([1, 1, 1, 0]);
    expect(nanMean(values, mask)).toBe(3);

    const extent = nanExtent(values, mask);
    expect(extent).toEqual({ min: 2, max: 4, count: 2 });
  });

  it("reports an empty extent rather than infinities", () => {
    const extent = nanExtent(Float64Array.from([NaN, NaN]));
    expect(extent.count).toBe(0);
    expect(Number.isNaN(extent.min)).toBe(true);
  });
});

describe("hashArray", () => {
  it("is stable for identical content and sensitive to a real change", () => {
    const a = Float64Array.from([1.5, 2.25, 3.125]);
    const b = Float64Array.from([1.5, 2.25, 3.125]);
    expect(hashArray(a)).toBe(hashArray(b));

    b[2] = 3.126;
    expect(hashArray(a)).not.toBe(hashArray(b));
  });

  it("ignores differences below the 1e-6 quantisation floor", () => {
    const a = Float64Array.from([10.0]);
    const b = Float64Array.from([10.0 + 1e-12]);
    expect(hashArray(a)).toBe(hashArray(b));
  });
});
